# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@interface :StrategiesApi "GET" "/strategies" function list_strategies(req::HTTP.Request;)::Vector{StrategySummary}
    error("Method not implemented")
end

@generated_handler :StrategiesApi :list_strategies :read function list_strategies_read(handler)
    function list_strategies_read_handler(req::HTTP.Request;)::Vector{StrategySummary}
        openapi_params = Dict{String,Any}()
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

@generated_handler :StrategiesApi :list_strategies :validate function list_strategies_validate(handler)
    function list_strategies_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        op = "list_strategies"

        return handler(req)
    end
end

@generated_handler :StrategiesApi :list_strategies :invoke function list_strategies_invoke(impl; post_invoke=nothing)
    function list_strategies_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.list_strategies(req::HTTP.Request;)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end


function registerStrategiesApi(router::HTTP.Router, impl; path_prefix::String="", optional_middlewares...)
    HTTP.register!(router, "GET", path_prefix * "/strategies", OpenAPI.Servers.middleware(impl, list_strategies_read, list_strategies_validate, list_strategies_invoke; optional_middlewares...))
    return router
end


"""
Macro to register a API route.

Usage examples:
@registerStrategiesApi ("/api/v1",["StrategiesApi"]) function list_strategies(req::HTTP.Request;)::Vector{StrategySummary}
    # ...
end
"""
macro registerStrategiesApi(config, func_def)
    # Ensure the second argument is a function definition
    if !Meta.isexpr(func_def, :function)
        error("The second argument must be a function definition")
    end
    
    # Handle the config parameter based on its type
    if config isa String || config isa Symbol
        # Simple case: only a route prefix
        prefix = config
        tags = String["StrategiesApi"]
        middleware = nothing
        interval = nothing
        cron = nothing
    elseif Meta.isexpr(config, :tuple)
        # Tuple form with multiple configuration parameters
        prefix = config.args[1]
        tags = length(config.args) > 1 ? config.args[2] : String["StrategiesApi"]
        middleware = length(config.args) > 2 ? config.args[3] : nothing
        interval = length(config.args) > 3 ? config.args[4] : nothing
        cron = length(config.args) > 4 ? config.args[5] : nothing
    else
        error("Invalid configuration parameter format")
    end

    func_name, return_type = parse_function_definition(func_def)
    
    return quote
        local result = $(esc(func_def))
        register_api_route(
            :StrategiesApi,
            result,
            $(esc(return_type));
            prefix=$(esc(prefix)),
            tags=$(esc(tags)),
            middleware=$(middleware),
            interval=$(esc(interval)),
            cron=$(esc(cron))
        )
        result
    end
end

macro registerStrategiesApi(func_def)
    if !Meta.isexpr(func_def, :function)
        error("The argument must be a function definition")
    end
    
    func_name, return_type = parse_function_definition(func_def)
    
    return quote
        local result = $(esc(func_def))
        register_api_route(
            :StrategiesApi,
            result,
            $(esc(return_type));
            prefix="/api/v1",
            tags=String["StrategiesApi"],
            middleware=nothing,
            interval=nothing,
            cron=nothing
        )
        result
    end
end


export @registerStrategiesApi

