# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@interface :AgentApi "POST" "/agents" function create_agent(req::HTTP.Request, create_agent_request::CreateAgentRequest;)::AgentSummary
    error("Method not implemented")
end
@interface :AgentApi "DELETE" "/agents/{agent_id}" function delete_agent(req::HTTP.Request, agent_id::String;)::Any
    error("Method not implemented")
end
@interface :AgentApi "GET" "/agents/{agent_id}" function get_agent(req::HTTP.Request, agent_id::String;)::AgentSummary
    error("Method not implemented")
end
@interface :AgentApi "GET" "/agents/{agent_id}/logs" function get_agent_logs(req::HTTP.Request, agent_id::String;)::Dict{String, Any}
    error("Method not implemented")
end
@interface :AgentApi "GET" "/agents/{agent_id}/output" function get_agent_output(req::HTTP.Request, agent_id::String;)::Dict{String, Any}
    error("Method not implemented")
end
@interface :AgentApi "GET" "/agents" function list_agents(req::HTTP.Request;)::Vector{AgentSummary}
    error("Method not implemented")
end
@interface :AgentApi "POST" "/agents/{agent_id}/webhook" function process_agent_webhook(req::HTTP.Request, agent_id::String; request_body=nothing,)::Any
    error("Method not implemented")
end
@interface :AgentApi "PUT" "/agents/{agent_id}" function update_agent(req::HTTP.Request, agent_id::String, agent_update::AgentUpdate;)::AgentSummary
    error("Method not implemented")
end

@generated_handler :AgentApi :create_agent :read function create_agent_read(handler)
    function create_agent_read_handler(req::HTTP.Request, create_agent_request::CreateAgentRequest;)::AgentSummary
        openapi_params = Dict{String,Any}()
        openapi_params["CreateAgentRequest"] = OpenAPI.Servers.to_param_type(CreateAgentRequest, String(req.body))
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

@generated_handler :AgentApi :create_agent :validate function create_agent_validate(handler)
    function create_agent_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        op = "create_agent"
        
        n = "CreateAgentRequest"
        v = get(openapi_params, n, nothing)
        isnothing(v) && throw(OpenAPI.ValidationException(;reason="missing parameter $n", operation_or_model=op))
        if !isnothing(v)
            if isa(v, OpenAPI.APIModel)
                OpenAPI.validate_properties(v)
                if !OpenAPI.check_required(v)
                    throw(OpenAPI.ValidationException(;reason="$n is missing required properties", operation_or_model=op))
                end
            end
        end

        return handler(req)
    end
end

@generated_handler :AgentApi :create_agent :invoke function create_agent_invoke(impl; post_invoke=nothing)
    function create_agent_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.create_agent(req::HTTP.Request, openapi_params["CreateAgentRequest"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

@generated_handler :AgentApi :delete_agent :read function delete_agent_read(handler)
    function delete_agent_read_handler(req::HTTP.Request, agent_id::String;)::Any
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["agent_id"] = OpenAPI.Servers.to_param(String, path_params, "agent_id", required=true, )
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

@generated_handler :AgentApi :delete_agent :validate function delete_agent_validate(handler)
    function delete_agent_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        op = "delete_agent"
        
        n = "agent_id"
        v = get(openapi_params, n, nothing)
        isnothing(v) && throw(OpenAPI.ValidationException(;reason="missing parameter $n", operation_or_model=op))
        if !isnothing(v)
            if isa(v, OpenAPI.APIModel)
                OpenAPI.validate_properties(v)
                if !OpenAPI.check_required(v)
                    throw(OpenAPI.ValidationException(;reason="$n is missing required properties", operation_or_model=op))
                end
            end
        end

        return handler(req)
    end
end

@generated_handler :AgentApi :delete_agent :invoke function delete_agent_invoke(impl; post_invoke=nothing)
    function delete_agent_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.delete_agent(req::HTTP.Request, openapi_params["agent_id"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

@generated_handler :AgentApi :get_agent :read function get_agent_read(handler)
    function get_agent_read_handler(req::HTTP.Request, agent_id::String;)::AgentSummary
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["agent_id"] = OpenAPI.Servers.to_param(String, path_params, "agent_id", required=true, )
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

@generated_handler :AgentApi :get_agent :validate function get_agent_validate(handler)
    function get_agent_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        op = "get_agent"
        
        n = "agent_id"
        v = get(openapi_params, n, nothing)
        isnothing(v) && throw(OpenAPI.ValidationException(;reason="missing parameter $n", operation_or_model=op))
        if !isnothing(v)
            if isa(v, OpenAPI.APIModel)
                OpenAPI.validate_properties(v)
                if !OpenAPI.check_required(v)
                    throw(OpenAPI.ValidationException(;reason="$n is missing required properties", operation_or_model=op))
                end
            end
        end

        return handler(req)
    end
end

@generated_handler :AgentApi :get_agent :invoke function get_agent_invoke(impl; post_invoke=nothing)
    function get_agent_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.get_agent(req::HTTP.Request, openapi_params["agent_id"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

@generated_handler :AgentApi :get_agent_logs :read function get_agent_logs_read(handler)
    function get_agent_logs_read_handler(req::HTTP.Request, agent_id::String;)::Dict{String, Any}
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["agent_id"] = OpenAPI.Servers.to_param(String, path_params, "agent_id", required=true, )
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

@generated_handler :AgentApi :get_agent_logs :validate function get_agent_logs_validate(handler)
    function get_agent_logs_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        op = "get_agent_logs"
        
        n = "agent_id"
        v = get(openapi_params, n, nothing)
        isnothing(v) && throw(OpenAPI.ValidationException(;reason="missing parameter $n", operation_or_model=op))
        if !isnothing(v)
            if isa(v, OpenAPI.APIModel)
                OpenAPI.validate_properties(v)
                if !OpenAPI.check_required(v)
                    throw(OpenAPI.ValidationException(;reason="$n is missing required properties", operation_or_model=op))
                end
            end
        end

        return handler(req)
    end
end

@generated_handler :AgentApi :get_agent_logs :invoke function get_agent_logs_invoke(impl; post_invoke=nothing)
    function get_agent_logs_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.get_agent_logs(req::HTTP.Request, openapi_params["agent_id"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

@generated_handler :AgentApi :get_agent_output :read function get_agent_output_read(handler)
    function get_agent_output_read_handler(req::HTTP.Request, agent_id::String;)::Dict{String, Any}
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["agent_id"] = OpenAPI.Servers.to_param(String, path_params, "agent_id", required=true, )
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

@generated_handler :AgentApi :get_agent_output :validate function get_agent_output_validate(handler)
    function get_agent_output_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        op = "get_agent_output"
        
        n = "agent_id"
        v = get(openapi_params, n, nothing)
        isnothing(v) && throw(OpenAPI.ValidationException(;reason="missing parameter $n", operation_or_model=op))
        if !isnothing(v)
            if isa(v, OpenAPI.APIModel)
                OpenAPI.validate_properties(v)
                if !OpenAPI.check_required(v)
                    throw(OpenAPI.ValidationException(;reason="$n is missing required properties", operation_or_model=op))
                end
            end
        end

        return handler(req)
    end
end

@generated_handler :AgentApi :get_agent_output :invoke function get_agent_output_invoke(impl; post_invoke=nothing)
    function get_agent_output_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.get_agent_output(req::HTTP.Request, openapi_params["agent_id"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

@generated_handler :AgentApi :list_agents :read function list_agents_read(handler)
    function list_agents_read_handler(req::HTTP.Request;)::Vector{AgentSummary}
        openapi_params = Dict{String,Any}()
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

@generated_handler :AgentApi :list_agents :validate function list_agents_validate(handler)
    function list_agents_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        op = "list_agents"

        return handler(req)
    end
end

@generated_handler :AgentApi :list_agents :invoke function list_agents_invoke(impl; post_invoke=nothing)
    function list_agents_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.list_agents(req::HTTP.Request;)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

@generated_handler :AgentApi :process_agent_webhook :read function process_agent_webhook_read(handler)
    function process_agent_webhook_read_handler(req::HTTP.Request, agent_id::String; request_body=nothing,)::Any
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["agent_id"] = OpenAPI.Servers.to_param(String, path_params, "agent_id", required=true, )
        openapi_params["request_body"] = OpenAPI.Servers.to_param_type(Dict{String, Any}, String(req.body))
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

@generated_handler :AgentApi :process_agent_webhook :validate function process_agent_webhook_validate(handler)
    function process_agent_webhook_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        op = "process_agent_webhook"
        
        n = "agent_id"
        v = get(openapi_params, n, nothing)
        isnothing(v) && throw(OpenAPI.ValidationException(;reason="missing parameter $n", operation_or_model=op))
        if !isnothing(v)
            if isa(v, OpenAPI.APIModel)
                OpenAPI.validate_properties(v)
                if !OpenAPI.check_required(v)
                    throw(OpenAPI.ValidationException(;reason="$n is missing required properties", operation_or_model=op))
                end
            end
        end
        
        n = "request_body"
        v = get(openapi_params, n, nothing)
        if !isnothing(v)
            if isa(v, OpenAPI.APIModel)
                OpenAPI.validate_properties(v)
                if !OpenAPI.check_required(v)
                    throw(OpenAPI.ValidationException(;reason="$n is missing required properties", operation_or_model=op))
                end
            end
        end

        return handler(req)
    end
end

@generated_handler :AgentApi :process_agent_webhook :invoke function process_agent_webhook_invoke(impl; post_invoke=nothing)
    function process_agent_webhook_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.process_agent_webhook(req::HTTP.Request, openapi_params["agent_id"]; request_body=get(openapi_params, "request_body", nothing),)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

@generated_handler :AgentApi :update_agent :read function update_agent_read(handler)
    function update_agent_read_handler(req::HTTP.Request, agent_id::String, agent_update::AgentUpdate;)::AgentSummary
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["agent_id"] = OpenAPI.Servers.to_param(String, path_params, "agent_id", required=true, )
        openapi_params["AgentUpdate"] = OpenAPI.Servers.to_param_type(AgentUpdate, String(req.body))
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

@generated_handler :AgentApi :update_agent :validate function update_agent_validate(handler)
    function update_agent_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        op = "update_agent"
        
        n = "agent_id"
        v = get(openapi_params, n, nothing)
        isnothing(v) && throw(OpenAPI.ValidationException(;reason="missing parameter $n", operation_or_model=op))
        if !isnothing(v)
            if isa(v, OpenAPI.APIModel)
                OpenAPI.validate_properties(v)
                if !OpenAPI.check_required(v)
                    throw(OpenAPI.ValidationException(;reason="$n is missing required properties", operation_or_model=op))
                end
            end
        end
        
        n = "AgentUpdate"
        v = get(openapi_params, n, nothing)
        isnothing(v) && throw(OpenAPI.ValidationException(;reason="missing parameter $n", operation_or_model=op))
        if !isnothing(v)
            if isa(v, OpenAPI.APIModel)
                OpenAPI.validate_properties(v)
                if !OpenAPI.check_required(v)
                    throw(OpenAPI.ValidationException(;reason="$n is missing required properties", operation_or_model=op))
                end
            end
        end

        return handler(req)
    end
end

@generated_handler :AgentApi :update_agent :invoke function update_agent_invoke(impl; post_invoke=nothing)
    function update_agent_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.update_agent(req::HTTP.Request, openapi_params["agent_id"], openapi_params["AgentUpdate"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end


function registerAgentApi(router::HTTP.Router, impl; path_prefix::String="", optional_middlewares...)
    HTTP.register!(router, "POST", path_prefix * "/agents", OpenAPI.Servers.middleware(impl, create_agent_read, create_agent_validate, create_agent_invoke; optional_middlewares...))
    HTTP.register!(router, "DELETE", path_prefix * "/agents/{agent_id}", OpenAPI.Servers.middleware(impl, delete_agent_read, delete_agent_validate, delete_agent_invoke; optional_middlewares...))
    HTTP.register!(router, "GET", path_prefix * "/agents/{agent_id}", OpenAPI.Servers.middleware(impl, get_agent_read, get_agent_validate, get_agent_invoke; optional_middlewares...))
    HTTP.register!(router, "GET", path_prefix * "/agents/{agent_id}/logs", OpenAPI.Servers.middleware(impl, get_agent_logs_read, get_agent_logs_validate, get_agent_logs_invoke; optional_middlewares...))
    HTTP.register!(router, "GET", path_prefix * "/agents/{agent_id}/output", OpenAPI.Servers.middleware(impl, get_agent_output_read, get_agent_output_validate, get_agent_output_invoke; optional_middlewares...))
    HTTP.register!(router, "GET", path_prefix * "/agents", OpenAPI.Servers.middleware(impl, list_agents_read, list_agents_validate, list_agents_invoke; optional_middlewares...))
    HTTP.register!(router, "POST", path_prefix * "/agents/{agent_id}/webhook", OpenAPI.Servers.middleware(impl, process_agent_webhook_read, process_agent_webhook_validate, process_agent_webhook_invoke; optional_middlewares...))
    HTTP.register!(router, "PUT", path_prefix * "/agents/{agent_id}", OpenAPI.Servers.middleware(impl, update_agent_read, update_agent_validate, update_agent_invoke; optional_middlewares...))
    return router
end


"""
Macro to register a API route.

Usage examples:
@registerAgentApi ("/api/v1",["AgentApi"]) function create_agent(req::HTTP.Request, create_agent_request::CreateAgentRequest;)::AgentSummary
    # ...
end
@registerAgentApi ("/api/v1",["AgentApi"]) function delete_agent(req::HTTP.Request, agent_id::String;)::Any
    # ...
end
@registerAgentApi ("/api/v1",["AgentApi"]) function get_agent(req::HTTP.Request, agent_id::String;)::AgentSummary
    # ...
end
@registerAgentApi ("/api/v1",["AgentApi"]) function get_agent_logs(req::HTTP.Request, agent_id::String;)::Dict{String, Any}
    # ...
end
@registerAgentApi ("/api/v1",["AgentApi"]) function get_agent_output(req::HTTP.Request, agent_id::String;)::Dict{String, Any}
    # ...
end
@registerAgentApi ("/api/v1",["AgentApi"]) function list_agents(req::HTTP.Request;)::Vector{AgentSummary}
    # ...
end
@registerAgentApi ("/api/v1",["AgentApi"]) function process_agent_webhook(req::HTTP.Request, agent_id::String; request_body=nothing,)::Any
    # ...
end
@registerAgentApi ("/api/v1",["AgentApi"]) function update_agent(req::HTTP.Request, agent_id::String, agent_update::AgentUpdate;)::AgentSummary
    # ...
end
"""
macro registerAgentApi(config, func_def)
    # Ensure the second argument is a function definition
    if !Meta.isexpr(func_def, :function)
        error("The second argument must be a function definition")
    end
    
    # Handle the config parameter based on its type
    if config isa String || config isa Symbol
        # Simple case: only a route prefix
        prefix = config
        tags = String["AgentApi"]
        middleware = nothing
        interval = nothing
        cron = nothing
    elseif Meta.isexpr(config, :tuple)
        # Tuple form with multiple configuration parameters
        prefix = config.args[1]
        tags = length(config.args) > 1 ? config.args[2] : String["AgentApi"]
        middleware = length(config.args) > 2 ? config.args[3] : nothing
        interval = length(config.args) > 3 ? config.args[4] : nothing
        cron = length(config.args) > 4 ? config.args[5] : nothing
    else
        error("Invalid configuration parameter format")
    end

    func_name, return_type = parse_function_definition(func_def)
    
    return quote
        local result = $(esc(func_def))
        register_api_route(
            :AgentApi,
            result,
            $(esc(return_type));
            prefix=$(esc(prefix)),
            tags=$(esc(tags)),
            middleware=$(middleware),
            interval=$(esc(interval)),
            cron=$(esc(cron))
        )
        result
    end
end

macro registerAgentApi(func_def)
    if !Meta.isexpr(func_def, :function)
        error("The argument must be a function definition")
    end
    
    func_name, return_type = parse_function_definition(func_def)
    
    return quote
        local result = $(esc(func_def))
        register_api_route(
            :AgentApi,
            result,
            $(esc(return_type));
            prefix="/api/v1",
            tags=String["AgentApi"],
            middleware=nothing,
            interval=nothing,
            cron=nothing
        )
        result
    end
end


export @registerAgentApi

